# Generated by Django 2.0 on 2018-06-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
