# Generated by Django 2.0 on 2018-05-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='list_of_values',
        ),
        migrations.AddField(
            model_name='metric_result',
            name='list_of_values',
            field=models.CharField(default='', help_text='Values of one Metric', max_length=5000),
        ),
    ]
