# Generated by Django 2.0 on 2018-04-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_number',
            field=models.IntegerField(help_text='Number Of Step', unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(choices=[('VOIP_TEST', 'VOIP_TEST'), ('DATA_WAN_LAN', 'DATA_WAN_LAN'), ('DATA_WAN_WLAN', 'DATA_WAN_WLAN'), ('DATA_LAN_WLAN', 'DATA_LAN_WLAN'), ('P2P', 'P2P'), ('IPTV', 'IPTV'), ('WebUI', 'WEBUI')], max_length=50, unique=True),
        ),
    ]
