# Generated by Django 2.0 on 2018-06-29 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric_result',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 16, 57, 4, 757518)),
        ),
        migrations.AlterField(
            model_name='step_result',
            name='metrics',
            field=models.CharField(default='N/A', help_text='metrics', max_length=50000),
        ),
    ]
