# Generated by Django 2.0 on 2018-04-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_result',
            name='progress',
            field=models.CharField(default='0', help_text='progress', max_length=200),
        ),
        migrations.AddField(
            model_name='test_result',
            name='progress',
            field=models.CharField(default='0', help_text='progress', max_length=200),
        ),
    ]
