# Generated by Django 2.0 on 2018-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0002_auto_20180410_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='values',
            field=models.CharField(default='', help_text='Values of one Metric', max_length=5000),
        ),
    ]
