# Generated by Django 2.0 on 2018-04-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0002_auto_20180404_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('THROUGHPUT', 'THROUGHPUT'), ('PACKET_LOSS', 'PACKET_LOSS'), ('NUMBER_OF_CONNECTION', 'NUMBER_OF_CONNECTIONS'), ('PESQ_UPSTREAM', 'PESQ_UPSTREAM'), ('PESQ_DOWNSTREAM', 'PESQ_DOWNSTREAM'), ('ONE_WAY_DELAY_UPSTREAM', 'ONE_WAY_DELAY_UPSTREAM'), ('ONE_WAY_DELAY_DOWNSTREAM', 'ONE_WAY_DELAY_DOWNSTREAM')], max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='metrics',
            field=models.ManyToManyField(to='Robustness.Metric'),
        ),
    ]
