# Generated by Django 2.0 on 2018-06-14 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0002_config_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_time',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
