# Generated by Django 2.0 on 2018-07-04 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0002_auto_20180629_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(choices=[('THROUGHPUT', 'THROUGHPUT'), ('PACKET_LOSS', 'PACKET_LOSS'), ('NUMBER_OF_CONNECTION', 'NUMBER_OF_CONNECTIONS'), ('PESQ_UPSTREAM', 'PESQ_UPSTREAM'), ('PESQ_DOWNSTREAM', 'PESQ_DOWNSTREAM'), ('ONE_WAY_DELAY_UPSTREAM', 'ONE_WAY_DELAY_UPSTREAM'), ('ONE_WAY_DELAY_DOWNSTREAM', 'ONE_WAY_DELAY_DOWNSTREAM'), ('N/A', 'N/A'), ('CPU_USAGE', 'CPU_USAGE'), ('MEMORY_USAGE', 'MEMORY_USAGE')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='metric_result',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 4, 12, 5, 48, 174439)),
        ),
    ]
