# Generated by Django 2.0 on 2018-05-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0002_auto_20180502_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='id',
        ),
        migrations.AlterField(
            model_name='step',
            name='step_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(choices=[('VoIP', 'VoIP'), ('DATA_LAN_LAN', 'DATA_LAN_LAN'), ('DATA_LAN_WLAN_2.4_Ghz', 'DATA_LAN_WLAN_2.4_Ghz'), ('DATA_LAN_WLAN_5_Ghz', 'DATA_LAN_WLAN_5_Ghz'), ('DATA_WAN_WLAN_5_Ghz', 'DATA_WAN_WLAN_5_Ghz'), ('1xIPTV_WLAN_5_Ghz', '1xIPTV_WLAN_5_Ghz'), ('2xIPTV_WLAN_5_Ghz', '2xIPTV_WLAN_5_Ghz'), ('P2P_WLAN_5_Ghz', 'P2P_WLAN_5_Ghz'), ('2xIPTV_LAN', '2xIPTV_LAN'), ('WEBUI', 'WEBUI')], max_length=50, unique=True),
        ),
    ]
