# Generated by Django 2.0 on 2018-09-14 15:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0003_auto_20180704_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric_result',
            name='gateway_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_result',
            name='gateway_name',
            field=models.CharField(default='Generic2', help_text='Gateway Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='metric_result',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 14, 15, 25, 51, 886769)),
        ),
    ]
