# Generated by Django 2.0 on 2018-04-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0003_auto_20180404_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(choices=[('VOIP_TEST', 'VOIP_TEST'), ('DATA_LAN_LAN', 'DATA_LAN_LAN'), ('DATA_LAN_WLAN_2.4_Ghz', 'DATA_LAN_WLAN_2.4_Ghz'), ('DATA_LAN_WLAN_5_Ghz', 'DATA_LAN_WLAN_5_Ghz'), ('DATA_WAN_WLAN_5_Ghz', 'DATA_WAN_WLAN_5_Ghz'), ('IPTV_WLAN_5_Ghz', 'IPTV_WLAN_5_Ghz'), ('P2P_WLAN_5_Ghz', 'P2P_WLAN_5_Ghz'), ('IPTV_LAN', 'IPTV_LAN'), ('WEBUI', 'WEBUI')], max_length=50, unique=True),
        ),
    ]
