# Generated by Django 2.0 on 2018-04-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0004_auto_20180404_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Step', max_length=200)),
                ('description', models.CharField(help_text='Short Description for Test', max_length=5000)),
                ('step_number', models.IntegerField(help_text='Number Of Step', unique=True)),
                ('state', models.CharField(default='Unfinished', help_text='State', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Result',
            fields=[
                ('name', models.CharField(help_text='Name of the Test ', max_length=200)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='Unfinished', help_text='State', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(choices=[('THROUGHPUT', 'THROUGHPUT'), ('PACKET_LOSS', 'PACKET_LOSS'), ('NUMBER_OF_CONNECTION', 'NUMBER_OF_CONNECTIONS'), ('PESQ_UPSTREAM', 'PESQ_UPSTREAM'), ('PESQ_DOWNSTREAM', 'PESQ_DOWNSTREAM'), ('ONE_WAY_DELAY_UPSTREAM', 'ONE_WAY_DELAY_UPSTREAM'), ('ONE_WAY_DELAY_DOWNSTREAM', 'ONE_WAY_DELAY_DOWNSTREAM'), ('N/A', 'N/A')], max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='test_result',
            name='metrics',
            field=models.ManyToManyField(to='Robustness.Metric'),
        ),
        migrations.AddField(
            model_name='step_result',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Robustness.Test_Result'),
        ),
    ]
