# Generated by Django 2.0 on 2018-04-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0005_auto_20180405_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(help_text='Name of the Step', max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='step_result',
            name='ID',
        ),
        migrations.AddField(
            model_name='step_result',
            name='ID',
            field=models.ManyToManyField(to='Robustness.Test_Result'),
        ),
    ]
