# Generated by Django 2.0 on 2018-04-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Robustness', '0006_auto_20180405_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step_result',
            name='step_number',
            field=models.IntegerField(help_text='Number Of Step'),
        ),
    ]
